version: '3'
services:
  taas-apis:
      container_name: taas-apis
      build:
        context: .
        dockerfile: ./docker/Dockerfile
      environment:
        - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
        - ES_HOST=http://elasticsearch:9200
      ports:
        - '3000:3000'
      depends_on:
        - postgres
        - elasticsearch
      restart: always


  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    environment:
    - discovery.type=single-node
    ports:
    - 9200:9200

